### ISSUE TITLE
Convert to Maven project / Upgrade to Jena 3.0.1

### ISSUE THREAD

**Issue by Aklakan** [saleem-muhammad/feasible#1]
... or if you dislike maven, use gradle or sbt - just use _something_ and deploy the artifacts to either maven central (we have write privileges for all artifacts in the group org.aksw.*) or to http://maven.aksw.org.
And please remove the .eclipse, .settings and .classpath folders and add them to .gitignore!

This actually goes for any of our projects that does not meet this level of quality, but since my work _indirectly_ depends on this one, I have personal interest in this project getting distributed in a meaningful way ;)

The project is referenced by [Iguana](https://github.com/AKSW/IGUANA), which in turn is referenced by [Iguana-Extended](https://github.com/AKSW/IGUANA-Extended). Feasible has lib folder containing jars, whereas Iguana has a lib folder containing a feasible-1.0.jar which contains the feasible dependencies as jars! Such a project setup is nearly useless in a collaborative environment. Its really a waste of time always having to figure out and hack around build problems due to best practices not being followed.
For instance, due to the feasible jar containing further jars, it happened that ancient versions of jena were become included in my standalone jar from iguana-extended although mvn dependency:tree gives no hint about the origin.

Its fine to ship jar files with a release of a system in order for the release to be self contained - but for development this kind of distribution is unsuitable.

**Comment by saleem-muhammad** [comment]
done
